CREATE TABLE PRODUCT
(
    ID          INT PRIMARY KEY,
    TITRE       VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    IMAGE       VARCHAR(255) NOT NULL,
    PRIX        DECIMAL(10, 2)     NOT NULL
);